version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your-app-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your-postgres-password
      - POSTGRES_DB=products
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:13
    container_name: postgres-products
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-postgres-password
      POSTGRES_DB: products
